// <auto-generated />
using System;
using Flashcards.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flashcards.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220411234120_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Flashcards.Models.Collection", b =>
                {
                    b.Property<int>("Id_collection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_on")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_collection");

                    b.ToTable("Collection");
                });

            modelBuilder.Entity("Flashcards.Models.Collection_user", b =>
                {
                    b.Property<int>("Id_collection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Id_user")
                        .HasColumnType("int");

                    b.Property<string>("Rights")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("Study_time")
                        .HasColumnType("bigint");

                    b.HasKey("Id_collection");

                    b.ToTable("Collection_user");
                });

            modelBuilder.Entity("Flashcards.Models.Flashcard", b =>
                {
                    b.Property<int>("Id_flashcard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Id_collection")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_flashcard");

                    b.ToTable("Flashcard");
                });

            modelBuilder.Entity("Flashcards.Models.Flashcard_user", b =>
                {
                    b.Property<int>("Id_flashcard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Id_user")
                        .HasColumnType("int");

                    b.Property<string>("Memorized")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_flashcard");

                    b.ToTable("Flashcard_user");
                });

            modelBuilder.Entity("Flashcards.Models.User", b =>
                {
                    b.Property<int>("Id_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("First_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("Is_admin")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_user");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
